In [40]:
import numpy as np

a = np.zeros ([5, 5, 3])
a [1, 2] = 1
print (a[1, 2])
a [1, 2, 0] = 3

b = 3
 
if b not in a[1, 2]:
    print ("a aaa" )

[1. 1. 1.]


In [49]:
c = (1, 2)
print (a)
print ("_____")
print (a[c])
print ("_____")
print (a[1, 2])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [3. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
_____
[3. 1. 1.]
_____
[3. 1. 1.]


In [71]:
import numpy as np
# create a numpy array
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

ar = x[1, x[1] != 4]
ar

array([5, 6])

In [75]:
l = [1, 2, 3, 4]
l.index(2)

1

In [81]:
a = 1
a +=1
a 

2

In [89]:
v = np.array ([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 7])

v-b
max (abs (v-b))

2

In [97]:
a = np.array ([0, 1, 2, 3])
p = np.ones ([5, 5, 4])
r = np.ones([5, 5, 4]) *2



sum (p[1]*r[1])

array([10., 10., 10., 10.])

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [4]:
import numpy as np

policy = np.zeros([5, 4])
policy[:, :] = 0.25
policy

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [6]:
for n in range (10):
    print (n)
    if n > 3:
        break

0
1
2
3
4


In [13]:
rewards = [1, 2, 3, 4, 0]
rewards[-1] += 10
rewards[-1] += 10
rewards.append(0)
rewards[-1] += 10
rewards[-1] += 10
rewards

[1, 2, 3, 4, 20, 20]

In [16]:
r = []
r.append(0)
r[-1] += 10
r

[10]

In [27]:
S = [1, 2, 3, 4, 1, 2,3,4,1,2,3,4,1,2,3,4]

index = [i for i, e in enumerate(S[:15]) if e == 4]
index

[3, 7, 11]

In [24]:
list=['Code', 'Favtutor', 'java','Machine Learning', 'Students', 'Studies', 'java', 'python','java']
index = [i for i ,e in enumerate(list) if e == 'java']
print("Index for Value java: ", index)

Index for Value java:  [2, 6, 8]
