In [40]:
import numpy as np

a = np.zeros ([5, 5, 3])
a [1, 2] = 1
print (a[1, 2])
a [1, 2, 0] = 3

b = 3
 
if b not in a[1, 2]:
    print ("a aaa" )

[1. 1. 1.]


In [49]:
c = (1, 2)
print (a)
print ("_____")
print (a[c])
print ("_____")
print (a[1, 2])

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [3. 1. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
_____
[3. 1. 1.]
_____
[3. 1. 1.]


In [71]:
import numpy as np
# create a numpy array
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

ar = x[1, x[1] != 4]
ar

array([5, 6])

In [75]:
l = [1, 2, 3, 4]
l.index(2)

1

In [81]:
a = 1
a +=1
a 

2

In [89]:
v = np.array ([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 7])

v-b
max (abs (v-b))

2

In [97]:
a = np.array ([0, 1, 2, 3])
p = np.ones ([5, 5, 4])
r = np.ones([5, 5, 4]) *2



sum (p[1]*r[1])

array([10., 10., 10., 10.])

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])